fix mirror backfill from channels without channeldata
mamba-org/quetz pull request #108
Opened 2020-09-17 14:15 UTC by btel

2020-09-18 06:46 UTC, wolfv requested changes
can you squash the pre-commit run? 
The change with importing known platforms would be cool 

https://github.com/conda/conda/blob/61f1836824dc68a518227c4e829ca664d2dd6307/conda/base/constants.py#L63

2020-09-18 06:46 UTC, wolfv commented on quetz/main.py
> +            subdirs = ["linux-64", "win-64", "win-32", "osx-64"]
I wonder if we can import the list of known platforms from conda?

2020-09-18 13:05 UTC, btel commented
sure I will squash the pre-commit runs.

I will check also whether we can get the arch from conda, but this will add dependency on conda?

2020-09-18 13:32 UTC, wolfv commented
right i think we removed the depenedency on conda ... you can just copy-paste in that case.

2020-09-18 14:46 UTC, btel commented
ok, thanks, for reference here is the list of platforms from conda:

https://github.com/conda/conda/blob/a78a2387f26a188991d771967fc33aa1fb5bb810/conda/base/constants.py#L63

2020-09-23 08:33 UTC, btel commented
@wolfv good to merge

2020-09-23 08:36 UTC, merged