first modifications for language of TOS
mamba-org/quetz pull request #543
Opened 2022-06-23 09:38 UTC by MichaelKora

2022-06-23 09:43 UTC, martinRenou requested changes
Thanks!! Looks great. We probably need upload to support a `language` parameter as well?

2022-06-23 15:40 UTC, martinRenou commented on plugins/quetz_tos/tests/test_quetz_tos.py
> +    response = client.get('/api/tos', params=params)
is it equivalent to `response = client.get('/api/tos?language=FR')`?

2022-06-24 13:30 UTC, martinRenou commented on plugins/quetz_tos/quetz_tos/api.py
> +@router.get("/api/tos/?{lang}", tags=['Terms of Service'])
I guess this does not work?

For adding query parameters you can look at how it is done here: https://github.com/tiangolo/fastapi#create-it. See how they have the `"q"` query parameter.

So you probably want something like:
```python
@router.get("/api/tos", tags=['Terms of Service'])
def get_current_tos(lang: str = "EN", db: Session = Depends(get_db)):
```

And then this API will be called with `GET /api/tos?lang=FR`

2022-06-24 13:33 UTC, martinRenou commented on plugins/quetz_tos/quetz_tos/api.py
> +        db.query(TermsOfService).filter_by(language == f"{lang}").first()
Does it work? It seems `language` is not defined here?

For the code styling, `f"{lang}"` can simply be `lang`.

Maybe the following works? (fetch all terms of services and get the first one that matches the language)
```python
terms_of_services = (
    db.query(TermsOfService).order_by(TermsOfService.time_created.desc()).all()
)

current_tos = None
for tos in terms_of_services:
    if tos.language == lang:
        current_tos = tos
```

2022-06-24 13:34 UTC, martinRenou commented on plugins/quetz_tos/tests/test_quetz_tos.py
> +    response = client.get('/api/tos', params=params)
Maybe you could try `response = client.get('/api/tos?lang=FR')` if this does not work.

2022-06-24 13:35 UTC, martinRenou commented on plugins/quetz_tos/tests/test_quetz_tos.py
>      assert response.json()['filename'] == 'tos.txt'
The content of your FR terms of services file is `tos_fr.txt`, so you probably need to fix this line.

2022-06-29 13:48 UTC, martinRenou approved these changes
Thanks! To me this looks good.

@wolfv You'd probably want to have a look :)

2022-06-29 13:57 UTC, martinRenou commented
I am just a bit skeptical about the signing logic now.

Because it's one `TermsOfServices` object per-language, it's one `id` per-language. So when someone signs a specific version of the terms of services, they sign it for the language they read.
It's probably fine though?

2023-02-16 20:34 UTC, janjagusch commented
https://github.com/mamba-org/quetz/pull/552 got merged, so can we close this, @martinRenou, @MichaelKora?

2023-05-12 08:35 UTC, closed without merging